# Generated by Django 3.1.5 on 2021-01-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowed',
            options={'managed': True, 'verbose_name': 'Borrowed', 'verbose_name_plural': 'Borrowed'},
        ),
        migrations.AlterModelTable(
            name='borrowed',
            table='Borrowed',
        ),
    ]
